import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { rules } from "../rules/index.js";
import {
  extractContextUnits,
  getAiInstructionFiles,
} from "../utils/context-units.js";
import { createAutofixSession } from "./autofix-session.js";
import { loadConfig, mergeScanConfig } from "./config.js";
import { buildScanContext } from "./context.js";
import { scanRepository } from "./scanner.js";
import type { FixResult, Issue, ScanOptions } from "./types.js";

const compactFileName = "context-debt.compact.md";
const filePrecedence: Record<string, number> = {
  agents: 0,
  claude: 1,
  copilot: 2,
  codex: 3,
  windsurf: 4,
  "cursor-rule": 5,
  readme: 6,
};

export async function fixRepository(
  inputPath: string,
  options: ScanOptions = {},
  write = false,
): Promise<FixResult> {
  const rootDir = resolve(inputPath);
  const loadedConfig = loadConfig(rootDir, options.configPath);
  const config = mergeScanConfig(loadedConfig, {
    include: options.include,
    exclude: options.exclude,
    roots: options.roots,
  });
  const context = await buildScanContext(rootDir, config);
  const scanResult = await scanRepository(inputPath, options);
  const { edits, session } = createAutofixSession(rootDir);
  const issuesByRule = groupIssuesByRule(scanResult.issues);

  for (const rule of rules) {
    rule.autofix?.(context, issuesByRule.get(rule.id) ?? [], session);
  }

  session.replaceFile(
    compactFileName,
    "",
    buildCompactContext(context),
    "generated compact context suggestion",
  );

  const finalEdits = edits();
  if (write) {
    for (const edit of finalEdits) {
      writeFileSync(resolve(rootDir, edit.path), edit.after, "utf8");
    }
  }

  return {
    edits: finalEdits,
    generatedCompactPath: compactFileName,
    issueSummary: scanResult.summary,
    scannedPath: inputPath,
  };
}

function groupIssuesByRule(issues: Issue[]): Map<string, Issue[]> {
  const grouped = new Map<string, Issue[]>();

  for (const issue of issues) {
    const existing = grouped.get(issue.ruleId) ?? [];
    existing.push(issue);
    grouped.set(issue.ruleId, existing);
  }

  return grouped;
}

function buildCompactContext(
  context: Awaited<ReturnType<typeof buildScanContext>>,
): string {
  const canonicalByNormalized = new Map<
    string,
    { file: string; raw: string; kind: string }
  >();

  for (const file of [...getAiInstructionFiles(context)].sort(compareFiles)) {
    for (const unit of extractContextUnits(file)) {
      if (!canonicalByNormalized.has(unit.normalized)) {
        canonicalByNormalized.set(unit.normalized, {
          file: file.path,
          raw: unit.raw,
          kind: file.kind,
        });
      }
    }
  }

  const lines = [
    "# Compact AI Context",
    "",
    "Generated by `context-debt fix` from canonical instruction units.",
    "",
    ...[...canonicalByNormalized.values()].map(
      (unit) => `- ${stripListMarker(unit.raw)}`,
    ),
  ];

  return `${lines.join("\n").trimEnd()}\n`;
}

function compareFiles(
  left: ReturnType<typeof getAiInstructionFiles>[number],
  right: ReturnType<typeof getAiInstructionFiles>[number],
): number {
  const precedenceDiff =
    (filePrecedence[left.kind] ?? 99) - (filePrecedence[right.kind] ?? 99);

  if (precedenceDiff !== 0) {
    return precedenceDiff;
  }

  return left.path.localeCompare(right.path);
}

function stripListMarker(value: string): string {
  return value.replace(/^[-*]\s+/u, "").replace(/^\d+\.\s+/u, "");
}
