"""
AgentReady — LLM Analyser (Phase 1 + Phase 2)

Phase 1: Collect — mechanical file reading, no reasoning.
Phase 2: Analyse — LLM reads the actual code and produces a structured
         JSON understanding of the repository.

Uses LiteLLM — works with Anthropic, OpenAI, and Google providers.
"""

from __future__ import annotations

import json
import random
import time
from pathlib import Path
from typing import Any

# ── Constants ─────────────────────────────────────────────────────────────────

SKIP_DIRS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    "dist",
    "build",
    "target",
    ".next",
    ".nuxt",
    "out",
    "coverage",
    ".idea",
    ".vscode",
    ".gradle",
    ".sass-cache",
    "tmp",
    "temp",
}

# AgentReady-generated files — never feed back to Opus as source code
SKIP_AGENT_FILES = {
    "AGENTS.md",
    "CLAUDE.md",
    ".cursorrules",  # generated by agent-ready
    "agent-context.json",
    "system_prompt.md",
    "mcp.json",
    "AGENTIC_EVAL.md",
    "openapi.yaml",  # generated by agent-ready
    "CODEOWNERS",  # generated by agent-ready
    "dependabot.yml",  # generated by agent-ready
}

SKIP_AGENT_DIRS = {
    "memory",
    "tools",
    ".agent-ready",  # custom questions starter
    "skills",  # generated by agent-ready
    "hooks",  # generated by agent-ready
}

# AgentReady workflow files installed INTO target repos.
# These describe the agent-ready tooling, NOT the application's domain.
# Feeding them to the analyser causes the LLM to treat "agentic-ready",
# "context drift", and "agent-context.json" as business domain concepts.
SKIP_AGENT_WORKFLOWS = {
    "agentic-ready.yml",
    "agentic-ready-eval.yml",
    "context-drift-detector.yml",
    "pr-review.yml",
}

SOURCE_EXTENSIONS = {
    ".py",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".java",
    ".go",
    ".rs",
    ".cs",
    ".rb",
    ".kt",
    ".swift",
    ".cpp",
    ".c",
    ".h",
    ".php",
}

CONFIG_FILES = [
    "package.json",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "go.mod",
    "Cargo.toml",
    "pyproject.toml",
    "requirements.txt",
    "setup.py",
    "setup.cfg",
    "Makefile",
    "Gemfile",
    ".env.example",
    ".env.sample",
    "docker-compose.yml",
    "Dockerfile",
]

OPENAPI_PATTERNS = [
    "openapi.yaml",
    "openapi.yml",
    "openapi.json",
    "swagger.yaml",
    "swagger.yml",
    "swagger.json",
]

MAX_SOURCE_FILES = 40
MAX_FILE_KB = 80

ANALYSIS_SCHEMA = """
{
  "project_name": "string",
  "description": "string — what the APPLICATION does in 1-2 sentences (not the CI/CD tooling)",
  "primary_language": "string — the single dominant language",
  "secondary_languages": ["string"],
  "frameworks": ["string — only frameworks actually found in dependency files"],
  "build_system": "maven|gradle|npm|yarn|pip|go|cargo|make|bundler|unknown",
  "runtime_version": "string — exact runtime version constraint (e.g. '>=3.11', 'node 20.x', 'java 17') from package files; empty string if not specified",
  "entry_point": "string — main entry point path relative to repo root, must exist in file tree",
  "test_command": "string — exact command to RUN the tests (not install/setup steps); e.g. 'pytest tests/' or 'npm test'",
  "build_command": "string — exact command to build",
  "install_command": "string — exact command to install dependencies",
  "run_command": "string — exact command to run the application",
  "architecture_summary": "string — 2-3 sentences on the APPLICATION system architecture",
  "domain_concepts": [
    {
      "term": "string — a term from the APPLICATION'S business or functional domain ONLY",
      "definition": "string — what it means in this specific application"
    }
  ],
  "restricted_write_paths": ["string — APPLICATION paths agents must NEVER modify (not CI tooling paths)"],
  "environment_variables": ["string — env var names found in the APPLICATION source code"],
  "key_components": [
    {"name": "string", "path": "string — must exist in file tree", "responsibility": "string"}
  ],
  "agent_safe_operations": ["string — specific safe operations in THIS application codebase"],
  "agent_forbidden_operations": ["string — specific forbidden operations in THIS application codebase"],
  "test_framework": "string",
  "test_directory": "string",
  "source_directories": ["string"],
  "module_layout": {"module-name": "path"},
  "naming_convention": "snake_case|camelCase|PascalCase|kebab-case",
  "structure_type": "monorepo|single-package|multi-module",
  "has_ci": true,
  "has_openapi": false,
  "potential_pitfalls": ["string — specific gotchas an AI agent will hit when working on the APPLICATION code"]
}
"""

ANALYSIS_SYSTEM = """\
You are a senior software architect performing a deep analysis of a codebase.
Your output drives the generation of AI agent scaffolding files.
Respond ONLY with a single valid JSON object matching the schema provided.
No markdown fences, no preamble, no explanation — raw JSON only.
All file paths must be relative to the repo root and must actually appear in the file tree.
Mark any value you cannot confirm with "TODO: verify" rather than guessing.

CRITICAL RULES for domain_concepts:
- Include ONLY terms from the APPLICATION'S business or functional domain.
  Examples of valid concepts: "Order", "Customer", "Frame" (bowling), "Payment", "Route".
- NEVER include CI/CD tooling, GitHub Actions workflows, or infrastructure concepts.
  Invalid examples: "agentic-ready", "context drift", "agent-context.json", "scaffolding",
  "LLM", "PR review", "workflow", "GitHub Actions". These are tooling — not the app's domain.
- If you see AgentReady workflow files in the CI configuration, ignore them entirely.
  They describe the AI tooling installed on top of this repo, not the application itself.

CRITICAL RULES for description and architecture_summary:
- Describe what the APPLICATION does for its end users, not what CI/CD does.
- Do not mention AgentReady, agent-context.json, context drift, or any AI tooling.

CRITICAL RULES for potential_pitfalls:
- Only list gotchas that an agent will hit when editing the APPLICATION code.
- Do not list CI workflow maintenance, agent-context.json updates, or scaffolding tasks.\
"""


# ── Phase 1: Collect ──────────────────────────────────────────────────────────


def collect(target: Path, quiet: bool = False) -> dict[str, Any]:
    if not quiet:
        print("  📂 Collecting repository files...")

    file_tree: list[str] = []
    source_files: dict[str, str] = {}
    config_files: dict[str, str] = {}
    ci_files: dict[str, str] = {}
    readme: str | None = None
    has_openapi = False

    for path in sorted(target.rglob("*")):
        rel = path.relative_to(target)
        if any(skip in rel.parts for skip in SKIP_DIRS):
            continue
        if any(skip in rel.parts for skip in SKIP_AGENT_DIRS):
            continue
        if path.is_file():
            # Exclude agent-ready generated files and its own workflow files from the tree
            if path.name in SKIP_AGENT_FILES:
                continue
            if path.name in SKIP_AGENT_WORKFLOWS:
                continue
            file_tree.append(str(rel))

    for name in ["README.md", "README.rst", "README.txt", "README"]:
        p = target / name
        if p.exists():
            readme = p.read_text(errors="ignore")[:6000]
            break

    for name in CONFIG_FILES:
        p = target / name
        if p.exists():
            config_files[name] = p.read_text(errors="ignore")[:3000]

    for ci_dir in [".github/workflows", ".gitea/workflows", ".circleci", ".gitlab"]:
        ci_path = target / ci_dir
        if ci_path.is_dir():
            for f in ci_path.iterdir():
                if f.is_file() and f.name not in SKIP_AGENT_WORKFLOWS:
                    ci_files[str(f.relative_to(target))] = f.read_text(errors="ignore")[:2000]

    for pattern in OPENAPI_PATTERNS:
        if list(target.rglob(pattern)):
            has_openapi = True
            break

    test_markers = {"test", "tests", "spec", "__tests__", "fixtures", "mocks"}
    collected = 0
    for ext in SOURCE_EXTENSIONS:
        if collected >= MAX_SOURCE_FILES:
            break
        for f in sorted(target.rglob(f"*{ext}")):
            if collected >= MAX_SOURCE_FILES:
                break
            rel = f.relative_to(target)
            if any(skip in rel.parts for skip in SKIP_DIRS):
                continue
            if any(marker in rel.parts for marker in test_markers):
                continue
            # Never feed AgentReady's own output back to the analysis model
            if f.name in SKIP_AGENT_FILES:
                continue
            if any(skip in rel.parts for skip in SKIP_AGENT_DIRS):
                continue
            if f.stat().st_size / 1024 > MAX_FILE_KB:
                continue
            try:
                source_files[str(rel)] = f.read_text(errors="ignore")[:3000]
                collected += 1
            except Exception:
                pass

    if not quiet:
        print(f"  📁 {len(file_tree)} files in tree")
        print(f"  📄 {len(source_files)} source files collected")

    return {
        "file_tree": file_tree[:300],
        "readme": readme,
        "config_files": config_files,
        "ci_files": ci_files,
        "source_files": source_files,
        "has_openapi": has_openapi,
    }


# ── Phase 2: LLM Analysis ─────────────────────────────────────────────────────


def _fact(value: Any, source: str, confidence: str) -> dict[str, Any]:
    return {"value": value, "source": source, "confidence": confidence}


def _not_found() -> dict[str, Any]:
    return {"value": None, "source": None, "confidence": "not_found"}


def extract_verified_facts(repo: dict[str, Any]) -> dict[str, Any]:
    """Mechanically extract verifiable facts from raw source files — no LLM.

    Each fact includes value, source (file + location), and confidence:
      high      — directly stated in source
      inferred  — deduced from conventions (e.g. Flask → likely 'flask run')
      not_found — no evidence in any source file
    """
    config = repo.get("config_files", {})
    ci = repo.get("ci_files", {})
    source = repo.get("source_files", {})
    readme = repo.get("readme", "") or ""
    file_tree = repo.get("file_tree", [])
    all_files = {**config, **ci, **source}
    if readme:
        all_files["README.md"] = readme

    facts: dict[str, Any] = {}

    # ── test_command ──────────────────────────────────────────────────────────
    pyproject = config.get("pyproject.toml", "")
    makefile = config.get("Makefile", "")

    if "[tool.pytest" in pyproject:
        facts["test_command"] = _fact("pytest", "pyproject.toml [tool.pytest]", "high")
    elif "pytest" in makefile:
        for line in makefile.splitlines():
            stripped = line.strip()
            if stripped.startswith("test") and "pytest" in stripped:
                cmd = stripped.split(":", 1)[-1].strip() or "pytest"
                facts["test_command"] = _fact(cmd, "Makefile", "high")
                break
        if "test_command" not in facts:
            facts["test_command"] = _fact("pytest", "Makefile", "high")
    else:
        # Scan CI workflows for test invocations
        for fname, content in ci.items():
            for line in content.splitlines():
                stripped = line.strip()
                if stripped.startswith("run:") and "pytest" in stripped:
                    cmd = stripped[4:].strip()
                    facts["test_command"] = _fact(cmd, fname, "high")
                    break
                if stripped.startswith("run:") and "npm test" in stripped:
                    facts["test_command"] = _fact("npm test", fname, "high")
                    break
            if "test_command" in facts:
                break
        if "test_command" not in facts:
            facts["test_command"] = _not_found()

    # ── install_command ───────────────────────────────────────────────────────
    if "pyproject.toml" in config or "setup.py" in config or "setup.cfg" in config:
        facts["install_command"] = _fact(
            "pip install -e .", "pyproject.toml / setup.py", "inferred"
        )
    elif "requirements.txt" in config:
        facts["install_command"] = _fact(
            "pip install -r requirements.txt", "requirements.txt", "high"
        )
    elif "package.json" in config:
        facts["install_command"] = _fact("npm install", "package.json", "inferred")
    elif "pom.xml" in config:
        facts["install_command"] = _fact("mvn install", "pom.xml", "inferred")
    elif "go.mod" in config:
        facts["install_command"] = _fact("go mod download", "go.mod", "inferred")
    else:
        facts["install_command"] = _not_found()

    # ── entry_point ───────────────────────────────────────────────────────────
    tree_set = set(file_tree)
    root_files = [
        f
        for f in [
            "main.py",
            "app.py",
            "index.py",
            "manage.py",
            "server.py",
            "index.js",
            "index.ts",
            "main.go",
            "main.java",
            "main.rs",
        ]
        if f in tree_set
    ]
    if root_files:
        ep = root_files[0]
        facts["entry_point"] = _fact(ep, "file_tree root", "high")
    else:
        # Look for if __name__ == "__main__" in source files
        for fpath, content in source.items():
            if '__name__ == "__main__"' in content or "__name__ == '__main__'" in content:
                facts["entry_point"] = _fact(fpath, f"{fpath} __main__ block", "high")
                break
        if "entry_point" not in facts:
            facts["entry_point"] = _not_found()

    # ── python_version ────────────────────────────────────────────────────────
    if "requires-python" in pyproject:
        for line in pyproject.splitlines():
            if "requires-python" in line:
                ver = line.split("=", 1)[-1].strip().strip('"').strip("'")
                facts["python_version"] = _fact(ver, "pyproject.toml requires-python", "high")
                break
    elif ".python-version" in config:
        ver = config[".python-version"].strip()
        facts["python_version"] = _fact(ver, ".python-version", "high")
    elif "runtime.txt" in config:
        ver = config["runtime.txt"].strip()
        facts["python_version"] = _fact(ver, "runtime.txt", "high")
    else:
        facts["python_version"] = _not_found()

    # ── restricted_paths ─────────────────────────────────────────────────────
    gitignore = config.get(".gitignore", "")
    generated_dirs = [
        line.strip().rstrip("/")
        for line in gitignore.splitlines()
        if line.strip()
        and not line.startswith("#")
        and any(kw in line for kw in ["dist", "build", "generated", ".env", "*.egg-info"])
    ]
    if generated_dirs:
        facts["restricted_paths"] = _fact(
            generated_dirs[:5], ".gitignore (build/generated/dist dirs)", "inferred"
        )
    else:
        facts["restricted_paths"] = _not_found()

    return facts


def _llm_call(model: str, system: str, prompt: str, max_tokens: int = 4096) -> str:
    """Single LiteLLM call with retry logic for overloaded errors."""
    try:
        import litellm
        import litellm.exceptions
    except ImportError:
        raise ImportError("litellm not installed. Run: pip install 'agent-ready[ai]'")

    last_error = None
    for attempt in range(3):
        try:
            response = litellm.completion(
                model=model,
                max_tokens=max_tokens,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": prompt},
                ],
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            # Handle overloaded / service unavailable errors across all providers
            err_str = str(e).lower()
            if any(
                x in err_str
                for x in ["529", "overloaded", "service unavailable", "rate limit", "429"]
            ):
                last_error = e
                if attempt < 2:
                    wait = (30 * (attempt + 1)) + random.uniform(0, 5)
                    print(
                        f"  ⚠️  API overloaded, retrying in {int(wait)}s... (attempt {attempt + 1}/3)"
                    )
                    time.sleep(wait)
                else:
                    raise last_error
            else:
                raise
    raise last_error


def analyse(
    repo: dict[str, Any],
    analysis_model: str,
    quiet: bool = False,
) -> dict[str, Any]:
    if not quiet:
        print(f"  🧠 Running deep code analysis with {analysis_model}...")
        print("     (this takes ~30–60 seconds)")

    parts: list[str] = [
        f"Analyse this repository and return JSON matching this schema:\n{ANALYSIS_SCHEMA}\n"
    ]

    if repo["readme"]:
        parts.append(f"## README\n{repo['readme']}")

    if repo["config_files"]:
        parts.append("## Config & Build Files")
        for name, content in repo["config_files"].items():
            parts.append(f"### {name}\n```\n{content}\n```")

    parts.append("## Complete File Tree\n" + "\n".join(repo["file_tree"]))

    if repo["ci_files"]:
        parts.append("## CI Configuration")
        for name, content in repo["ci_files"].items():
            parts.append(f"### {name}\n```\n{content}\n```")

    if repo["source_files"]:
        parts.append("## Production Source Files")
        for path, content in repo["source_files"].items():
            parts.append(f"### {path}\n```\n{content}\n```")

    prompt = "\n\n".join(parts)
    raw = _llm_call(model=analysis_model, system=ANALYSIS_SYSTEM, prompt=prompt, max_tokens=4096)

    if raw.startswith("```"):
        lines = raw.split("\n")
        raw = "\n".join(lines[1:])
    if raw.endswith("```"):
        raw = raw.rsplit("```", 1)[0]

    analysis = json.loads(raw.strip())
    analysis.setdefault("has_openapi", repo["has_openapi"])
    analysis["verified_facts"] = extract_verified_facts(repo)

    if not quiet:
        print(f"  ✓ Language: {analysis.get('primary_language', '?')}")
        print(f"  ✓ Frameworks: {', '.join(analysis.get('frameworks', [])) or 'none'}")
        print(f"  ✓ Entry point: {analysis.get('entry_point', '?')}")
        print(f"  ✓ Domain concepts: {len(analysis.get('domain_concepts', []))}")
        print(f"  ✓ Env vars found: {len(analysis.get('environment_variables', []))}")
        print(f"  ✓ Restricted paths: {len(analysis.get('restricted_write_paths', []))}")
        print(f"  ✓ Potential pitfalls: {len(analysis.get('potential_pitfalls', []))}")

    return analysis


def run(
    target: Path,
    analysis_model: str,
    quiet: bool = False,
) -> dict[str, Any]:
    """Run Phase 1 (collect) then Phase 2 (LLM analysis) and return analysis."""
    repo = collect(target, quiet=quiet)
    return analyse(repo, analysis_model=analysis_model, quiet=quiet)
