"""
AgentReady — LLM Generator (Phase 3)

Takes the structured analysis JSON produced by analyser.py and uses
an LLM to write each output file from scratch.

Uses LiteLLM — works with Anthropic, OpenAI, and Google providers.
"""

from __future__ import annotations

import json
import random
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

GENERATION_HEADER = (
    "<!-- Generated by AgentReady (LLM-first mode) | "
    "Dynamic section: do not edit manually. "
    "Static section in agent-context.json: safe to edit. -->"
)


# ── Token usage and cost tracking ─────────────────────────────────────────────

_usage_totals: dict = {
    "input_tokens": 0,
    "output_tokens": 0,
    "calls": 0,
    "by_model": {},
}

ANTHROPIC_PRICING: dict = {
    "claude-opus-4-6": {"input": 15.00, "output": 75.00},
    "claude-sonnet-4-6": {"input": 3.00, "output": 15.00},
    "claude-haiku-4-5": {"input": 0.80, "output": 4.00},
    "claude-haiku-4-5-20251001": {"input": 0.80, "output": 4.00},
}


def _calculate_cost(model: str, input_tokens: int, output_tokens: int) -> float:
    pricing = ANTHROPIC_PRICING.get(model, {"input": 0.0, "output": 0.0})
    return (
        input_tokens / 1_000_000 * pricing["input"] + output_tokens / 1_000_000 * pricing["output"]
    )


def get_usage_report() -> dict:
    total_cost = sum(
        _calculate_cost(model, data["input"], data["output"])
        for model, data in _usage_totals.get("by_model", {}).items()
    )
    return {**_usage_totals, "estimated_cost_usd": round(total_cost, 4)}


def reset_usage() -> None:
    _usage_totals["input_tokens"] = 0
    _usage_totals["output_tokens"] = 0
    _usage_totals["calls"] = 0
    _usage_totals["by_model"] = {}


# ── Grounding constraint for generation prompts ───────────────────────────────

_GROUNDING_RULES = """\
CRITICAL GROUNDING RULES — follow these before writing any fact:

1. Only assert facts that are directly present in the analysis input provided.
2. If a fact cannot be verified from the analysis input, write exactly:
   "Not determinable from source"
   Do not infer. Do not make reasonable assumptions. Do not write what is "likely" or "probably" true.
3. Commands (build, test, run, install) MUST come from the verified_facts dict in the analysis input.
   Use these confidence rules:
   - confidence=high: state the value as fact (e.g. "pytest")
   - confidence=inferred: state as "detected as likely: <value> — verify before use"
   - confidence=not_found: write "Not determinable from source" — NEVER invent a command
   Do NOT construct commands from framework knowledge (e.g. do not write "pytest -q --cov=app"
   unless this exact string appears in the analysis input or verified_facts).
4. File paths must come from the file_tree in the analysis input.
   Do not invent paths that seem plausible.
5. Domain concepts must come from the source code analysis.
   Do not describe what the domain concepts "typically" mean.
   If domain concepts cannot be extracted from the source: write
   "Not determinable from source — fill in agent-context.json static.domain_concepts after reviewing your codebase"
6. Python version, framework version, and tool versions must come from verified_facts.python_version.
   If confidence=not_found: write "Not determinable from source"
7. For restricted_write_paths: use verified_facts.restricted_paths if confidence=high or inferred.
   If confidence=not_found: write "Not determinable from source — fill in agent-context.json static.restricted_write_paths after reviewing your repo"
   Do NOT infer which paths should be restricted from framework conventions.
8. For directory structure: list ONLY directories and files present in the file_tree from the analysis input.
   Do NOT invent plausible directories (src/, tests/, docs/, etc.) that are not in the file_tree.

Violating these rules produces context files that hallucinate facts and make AI agents less reliable, not more.
The goal is grounded accuracy, not completeness.\
"""


# ── LiteLLM call with retry ───────────────────────────────────────────────────


def _call(
    model: str,
    prompt: str,
    max_tokens: int = 3000,
) -> str:
    try:
        import litellm
    except ImportError:
        raise ImportError("litellm not installed. Run: pip install 'agent-ready[ai]'")

    last_error = None
    for attempt in range(5):
        try:
            response = litellm.completion(
                model=model,
                max_tokens=max_tokens,
                messages=[{"role": "user", "content": prompt}],
            )
            if hasattr(response, "usage") and response.usage is not None:
                if model not in _usage_totals["by_model"]:
                    _usage_totals["by_model"][model] = {"input": 0, "output": 0}
                in_toks = (
                    getattr(response.usage, "input_tokens", None)
                    or getattr(response.usage, "prompt_tokens", 0)
                    or 0
                )
                out_toks = (
                    getattr(response.usage, "output_tokens", None)
                    or getattr(response.usage, "completion_tokens", 0)
                    or 0
                )
                _usage_totals["input_tokens"] += in_toks
                _usage_totals["output_tokens"] += out_toks
                _usage_totals["calls"] += 1
                _usage_totals["by_model"][model]["input"] += in_toks
                _usage_totals["by_model"][model]["output"] += out_toks
            return response.choices[0].message.content.strip()
        except Exception as e:
            err_str = str(e).lower()
            if any(
                x in err_str
                for x in ["529", "overloaded", "service unavailable", "rate limit", "429"]
            ):
                last_error = e
                if attempt < 4:
                    wait = (60 * (attempt + 1)) + random.uniform(0, 10)
                    print(
                        f"  ⚠️  API overloaded, retrying in {int(wait)}s... (attempt {attempt + 1}/5)"
                    )
                    time.sleep(wait)
                else:
                    raise last_error
            else:
                raise
    raise last_error


def _analysis_block(analysis: dict[str, Any]) -> str:
    return json.dumps(analysis, indent=2)


def _compact_analysis_for_prompt(analysis: dict[str, Any]) -> str:
    """Extract only the fields needed for skill/hook generation to avoid token bloat."""
    compact = {
        "primary_language": analysis.get("primary_language"),
        "frameworks": analysis.get("frameworks", []),
        "build_system": analysis.get("build_system"),
        "test_command": analysis.get("test_command"),
        "build_command": analysis.get("build_command"),
        "install_command": analysis.get("install_command"),
        "run_command": analysis.get("run_command"),
        "test_framework": analysis.get("test_framework"),
        "test_directory": analysis.get("test_directory"),
        "entry_point": analysis.get("entry_point"),
        "restricted_write_paths": analysis.get("restricted_write_paths", []),
        "potential_pitfalls": analysis.get("potential_pitfalls", []),
        "verified_facts": analysis.get("verified_facts", {}),
    }
    return json.dumps(compact, indent=2)


def _pitfalls_block(analysis: dict[str, Any]) -> str:
    pitfalls = analysis.get("potential_pitfalls", [])
    if not pitfalls:
        return "No pitfalls detected."
    return "\n".join(f"{i + 1}. {p}" for i, p in enumerate(pitfalls))


# ── agent-context.json ────────────────────────────────────────────────────────


def build_agent_context(
    analysis: dict[str, Any],
    existing_static: dict[str, Any] | None = None,
) -> str:
    # Use "TODO: add tests" when analyser found no test command, so agents don't fabricate test setup
    raw_test_cmd = analysis.get("test_command", "")
    test_command = (
        raw_test_cmd
        if raw_test_cmd and raw_test_cmd != "TODO: verify"
        else "TODO: no test suite detected — add tests first"
    )

    static = existing_static or {
        "project_name": analysis.get("project_name") or "",
        "description": analysis.get("description") or "",
        "primary_language": analysis.get("primary_language") or "",
        "runtime_version": analysis.get("runtime_version") or None,
        "frameworks": analysis.get("frameworks") or [],
        "entry_point": analysis.get("entry_point") or None,
        "test_command": test_command,
        "restricted_write_paths": analysis.get("restricted_write_paths") or [],
        "environment_variables": analysis.get("environment_variables") or [],
        "domain_concepts": [
            f"{c['term']}: {c['definition']}" for c in analysis.get("domain_concepts") or []
        ],
    }

    dynamic = {
        "last_scanned": datetime.now(timezone.utc).isoformat(),
        "secondary_languages": analysis.get("secondary_languages", []),
        "build_system": analysis.get("build_system", ""),
        "build_command": analysis.get("build_command", ""),
        "install_command": analysis.get("install_command", ""),
        "run_command": analysis.get("run_command", ""),
        "test_framework": analysis.get("test_framework", ""),
        "test_directory": analysis.get("test_directory", ""),
        "source_directories": analysis.get("source_directories", []),
        "module_layout": analysis.get("module_layout", {}),
        "architecture_summary": analysis.get("architecture_summary", ""),
        "key_components": analysis.get("key_components", []),
        "agent_safe_operations": analysis.get("agent_safe_operations", []),
        "agent_forbidden_operations": analysis.get("agent_forbidden_operations", []),
        "potential_pitfalls": analysis.get("potential_pitfalls", []),
        "conventions": {
            "naming": analysis.get("naming_convention", ""),
            "structure": analysis.get("structure_type", ""),
        },
        "has_ci": analysis.get("has_ci", False),
        "has_openapi": analysis.get("has_openapi", False),
    }

    return json.dumps({"static": static, "dynamic": dynamic}, indent=2)


# ── AGENTS.md ─────────────────────────────────────────────────────────────────


def generate_agents_md(model: str, analysis: dict[str, Any]) -> str:
    return _call(
        model,
        f"""\
Generate an AGENTS.md file for this repository.

AGENTS.md is the operating contract for GitHub Copilot and OpenAI agents.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write the following sections with SPECIFIC content — reference actual file paths,
class names, commands, and patterns found in this codebase. No generic advice.
If information is not in the analysis input, write "Not determinable from source" rather than inventing it.

{_GROUNDING_RULES}

1. ## Project Overview
   Name, what it actually does, language/framework/build tool.

2. ## Commands
   The exact verified commands — install, build, test, run, lint.

3. ## Safe Operations
   Specific things an agent IS permitted to do in this codebase.

4. ## Forbidden Operations
   Specific things an agent MUST NEVER do.
   Reference actual restricted_write_paths by name.

5. ## Domain Glossary
   Every term from domain_concepts, defined for zero-context readers.

6. ## Key Components
   Each entry from key_components: name, path, and responsibility.

7. ## Potential Pitfalls
   THIS SECTION IS CRITICAL. Write every item below verbatim as a warning.
   Do NOT summarise, generalise, or skip any item.

   Pitfalls found in this codebase:
{_pitfalls_block(analysis)}

   For each pitfall: what the agent will try to do, why it breaks things, what to do instead.

Write as if a senior engineer on this team authored it for an AI agent joining today.\
""",
    )


# ── CLAUDE.md ─────────────────────────────────────────────────────────────────


def generate_claude_md(model: str, analysis: dict[str, Any]) -> str:
    expected_skills = detect_skills(analysis)
    if expected_skills:
        skill_lines = "\n".join(
            f"   - `skills/{name}.md` — {_SKILL_DESCRIPTIONS.get(name, name)}"
            for name in expected_skills
        )
        skills_section = f"""

8. ## Available Skills
   Slash-command skill definitions generated for this repo. Each file is a
   self-contained instruction set grounded in the commands above.
{skill_lines}"""
    else:
        skills_section = ""

    return _call(
        model,
        f"""\
Generate a CLAUDE.md file for this repository.

CLAUDE.md is auto-loaded by Claude Code at the start of every session.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

Write the following sections as DIRECT INSTRUCTIONS.
Every rule must reference actual file paths, class names, or patterns.
No generic software engineering advice. If information is not in the analysis input,
write "Not determinable from source" rather than inventing it.

{_GROUNDING_RULES}

1. ## Critical Commands
   Use ONLY these commands — never invent alternatives:
   - Install:  {analysis.get("install_command", "see analysis")}
   - Build:    {analysis.get("build_command", "see analysis")}
   - Test:     {analysis.get("test_command", "see analysis")}
   - Run:      {analysis.get("run_command", "see analysis")}

2. ## Always Do
   6–8 specific rules for THIS codebase.

3. ## Never Do
   6–8 prohibitions referencing restricted_write_paths and agent_forbidden_operations.

4. ## Architecture Notes
   3–4 most important design decisions to understand.

5. ## Domain Context
   Key concepts for understanding the business logic.

6. ## Known Pitfalls — Read Before Writing Any Code
   THIS SECTION IS CRITICAL. Copy every pitfall below VERBATIM.
   Do NOT add generic advice. Do NOT skip any item.

   Pitfalls found in this codebase:
{_pitfalls_block(analysis)}

7. ## After Every Change
   Specific checklist including the test command.
{skills_section}\
""",
    )


# ── system_prompt.md ──────────────────────────────────────────────────────────


def generate_system_prompt(model: str, analysis: dict[str, Any]) -> str:
    return _call(
        model,
        f"""\
Generate a system_prompt.md file for this repository.

This file is the system prompt for ANY LLM working on this codebase.
Paste-ready into the system field of any LLM API call.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

{_GROUNDING_RULES}

Write in second person ("You are working on..."). Cover:
- What this project does
- Full tech stack: language, frameworks, build tool
- Exact commands to install, build, test, run
- What the LLM must never touch (reference restricted_write_paths by name)
- Domain concepts for understanding the business logic
- Coding conventions
- Key components and responsibilities
- Every pitfall verbatim:
{_pitfalls_block(analysis)}

Target ~400–600 words.\
""",
    )


# ── memory/schema.md ──────────────────────────────────────────────────────────


def generate_memory_schema(model: str, analysis: dict[str, Any]) -> str:
    return _call(
        model,
        f"""\
Generate a memory/schema.md file for this repository.

This file defines what an AI agent should track as working memory.
Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

{_GROUNDING_RULES}

Define a YAML schema for agent memory. Reference actual domain_concepts and key_components.

Include:
1. session_state — current task, status, phase
2. decisions_made — format for recording WHY a decision was made
3. files_modified — what to track about each changed file
4. tests_run — test results and coverage
5. open_questions — items needing human review
6. domain_state — language/framework-specific state worth tracking

Use YAML format with inline comments.\
""",
    )


# ── .github/copilot-instructions.md ──────────────────────────────────────────


def generate_copilot_instructions(model: str, analysis: dict[str, Any]) -> str:
    return _call(
        model,
        f"""\
Generate a .github/copilot-instructions.md file for this repository.

GitHub Copilot Chat automatically reads this file at the start of every session.
It is the Copilot equivalent of CLAUDE.md — architecture context auto-loaded into
every suggestion and chat response.

Start the file with this exact header on line 1:
{GENERATION_HEADER}

Repository analysis (derived from reading the actual code):
{_analysis_block(analysis)}

{_GROUNDING_RULES}

Write a concise, high-signal Copilot instructions file. Include:
1. One-paragraph project summary (what it does, primary language, key framework)
2. Build / test / run commands (exact, copy-pasteable)
3. Module layout — real directory names and what each contains
4. Restricted paths — files/directories an agent must never modify
5. Key domain concepts — 3-5 terms specific to this codebase with brief definitions
6. Top 3 pitfalls — the most likely mistakes a Copilot suggestion would make

Keep it under 400 words. Copilot has a limited context window — every word must earn
its place. No generic advice. Only facts derived from the actual code.\
""",
    )


# ── mcp.json ──────────────────────────────────────────────────────────────────


def generate_mcp_json(analysis: dict[str, Any]) -> str:
    project_name = analysis.get("project_name", "project").lower().replace(" ", "-")
    env_vars = {var: f"${{{var}}}" for var in analysis.get("environment_variables", [])[:5]}

    mcp = {
        "_comment": GENERATION_HEADER,
        "mcpServers": {
            f"{project_name}-agent-ready": {
                "command": "agent-ready-mcp",
                "args": [],
                "env": env_vars,
                "_note": (
                    "Exposes transform/score/evaluate/review_pr as MCP tools. "
                    "Install agent-ready to use: pip install agent-ready[ai]"
                ),
            }
        },
    }
    return json.dumps(mcp, indent=2)


# ── tools/refresh_context.py ─────────────────────────────────────────────────


def build_refresh_context_script(analysis: dict[str, Any]) -> str:
    """Generate a standalone tools/refresh_context.py script for the target repo.

    Running `python tools/refresh_context.py` from the repo root re-runs the
    AgentReady transformer in context-only mode, updating agent-context.json
    without touching the other generated files.
    """
    project = analysis.get("project_name", "this project")
    provider = analysis.get("_provider", "anthropic")
    return f"""\
#!/usr/bin/env python3
\"\"\"
Refresh agent-context.json for {project}.

Run this script from the repo root whenever the codebase changes significantly
(new modules, entry-point changes, new environment variables, etc.) to keep the
AI agent context up to date.

Usage:
    python tools/refresh_context.py [--provider PROVIDER] [--dry-run]

Requirements:
    pip install agent-ready[ai]
    export ANTHROPIC_API_KEY=...   # or whichever provider you use
\"\"\"
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DEFAULT_PROVIDER = "{provider}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Refresh agent-context.json")
    parser.add_argument(
        "--provider",
        default=DEFAULT_PROVIDER,
        help=f"LLM provider (default: {{DEFAULT_PROVIDER}})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would change without writing files",
    )
    args = parser.parse_args()

    cmd = [
        sys.executable, "-m", "agent_ready.cli",
        "--target", str(REPO_ROOT),
        "--provider", args.provider,
        "--only", "context",
    ]
    if args.dry_run:
        cmd.append("--dry-run")

    print(f"🔄 Refreshing agent-context.json for {project}...")
    print(f"   Provider : {{args.provider}}")
    print(f"   Target   : {{REPO_ROOT}}")
    if args.dry_run:
        print("   Mode     : dry-run (no files written)")
    print()

    result = subprocess.run(cmd, cwd=REPO_ROOT)
    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
"""


# ── .github/CODEOWNERS ───────────────────────────────────────────────────────


def build_codeowners(analysis: dict[str, Any]) -> str:
    """Generate .github/CODEOWNERS so AgentReady-generated files require human review.

    All generated context and workflow files are owned by '*' (the default owners
    defined in the repo/org settings). Adjust as needed — this is safe to edit.
    """
    restricted = analysis.get("restricted_write_paths", [])

    lines = [
        "# Auto-generated by AgentReady — safe to edit.",
        "# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners",
        "",
        "# AgentReady-generated context and workflow files require explicit human approval.",
        "# Replace '*' with your team handle, e.g. @myorg/platform-team",
        "agent-context.json        *",
        "AGENTS.md                 *",
        "CLAUDE.md                 *",
        ".cursorrules              *",
        "system_prompt.md          *",
        "mcp.json                  *",
        "AGENTIC_EVAL.md           *",
        "memory/                   *",
        "skills/                   *",
        "hooks/                    *",
        ".github/copilot-instructions.md  *",
        ".github/workflows/        *",
        "",
    ]

    if restricted:
        lines.append("# Restricted paths identified by AgentReady analysis")
        for path in restricted:
            clean = path.rstrip("/")
            if not clean.endswith("/") and "." not in clean.split("/")[-1]:
                clean += "/"
            lines.append(f"{clean}  *")
        lines.append("")

    return "\n".join(lines)


# ── openapi.yaml stub ─────────────────────────────────────────────────────────

_REST_FRAMEWORKS = {
    # Python
    "flask",
    "fastapi",
    "django",
    "starlette",
    "tornado",
    "aiohttp",
    # JavaScript / TypeScript
    "express",
    "koa",
    "hapi",
    "fastify",
    "nestjs",
    "nest",
    # Java
    "spring",
    "spring boot",
    "quarkus",
    "micronaut",
    "jersey",
    # Go
    "gin",
    "echo",
    "fiber",
    "chi",
    # Ruby
    "rails",
    "sinatra",
    # PHP
    "laravel",
    "symfony",
    "slim",
    # Rust
    "actix",
    "axum",
    "rocket",
}


def _is_rest_api(analysis: dict[str, Any]) -> bool:
    frameworks = {f.lower() for f in analysis.get("frameworks", [])}
    return bool(frameworks & _REST_FRAMEWORKS)


def build_openapi_stub(analysis: dict[str, Any]) -> str:
    """Generate a minimal openapi.yaml stub for REST API repositories.

    This is intentionally sparse — it establishes the file so the eval scorer
    awards the +5 openapi points, and gives developers a starting point to fill in.
    """
    project = analysis.get("project_name", "API")
    desc = analysis.get("description", f"REST API for {project}")
    lang = analysis.get("primary_language", "python").lower()
    frameworks = analysis.get("frameworks", [])
    framework = frameworks[0] if frameworks else "unknown"

    stub = {
        "openapi": "3.1.0",
        "info": {
            "title": project,
            "description": (
                f"{desc}\n\n"
                f"**Auto-generated stub** — fill in paths, schemas, and security.\n"
                f"Stack: {lang} / {framework}"
            ),
            "version": "0.1.0",
        },
        "paths": {
            "/health": {
                "get": {
                    "summary": "Health check",
                    "operationId": "health_check",
                    "responses": {
                        "200": {
                            "description": "Service is healthy",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {"status": {"type": "string"}},
                                    }
                                }
                            },
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}, "securitySchemes": {}},
    }

    import yaml

    header = (
        "# Auto-generated stub by AgentReady — fill in your actual paths and schemas.\n"
        "# Run: npx @redocly/cli lint openapi.yaml   to validate.\n"
    )
    return header + yaml.dump(stub, default_flow_style=False, sort_keys=False)


# ── .agent-ready/custom_questions.json ───────────────────────────────────────


def build_custom_questions_starter(analysis: dict[str, Any]) -> str:
    """Generate an example custom_questions.json so repo owners discover the hook.

    AgentReady eval v2 auto-loads this file when running evaluations.
    Users can add project-specific questions that the golden base set doesn't cover.
    """
    project = analysis.get("project_name", "this project")
    lang = analysis.get("primary_language", "python").lower()
    entry = analysis.get("entry_point", "main")

    example_questions = [
        {
            "_comment": (
                "Add project-specific eval questions here. "
                "AgentReady will merge these with the golden base set on every eval run. "
                "Remove the leading underscore from 'id' etc. to activate a question."
            ),
            "_id": f"custom_{lang}_001",
            "_version": "1.0",
            "_category": "commands",
            "_difficulty": "medium",
            "_prompt": f"How do you start {project} in development mode?",
            "_pass_threshold": 7,
            "_ground_truth_extraction": {
                "method": "static_then_llm",
                "static_sources": [
                    {
                        "type": "jsonpath",
                        "file": "agent-context.json",
                        "path": "$.static.run_command",
                    },
                ],
                "llm_prompt": f"What is the command to start {project} locally? Read {entry}.",
            },
            "_evaluation_criteria": f"Must include the exact run command for {project}.",
        },
        {
            "_comment": "Second example — domain-specific question",
            "_id": "custom_domain_001",
            "_version": "1.0",
            "_category": "domain",
            "_difficulty": "hard",
            "_prompt": "What happens to data when the application restarts?",
            "_pass_threshold": 8,
            "_ground_truth_extraction": {
                "method": "llm",
                "llm_prompt": "Does this application persist data across restarts? Read all source files carefully.",
            },
            "_evaluation_criteria": "Must accurately describe the persistence (or lack of) behaviour.",
        },
    ]

    return json.dumps(
        {
            "_instructions": (
                "Remove the leading underscore from field names (e.g. '_id' → 'id') "
                "to activate a question. All active questions are merged with the "
                "AgentReady golden base set on every evaluation run."
            ),
            "questions": example_questions,
        },
        indent=2,
    )


# ── .cursorrules ──────────────────────────────────────────────────────────────


def build_cursorrules(analysis: dict[str, Any]) -> str:
    """Generate a .cursorrules file from analysis data.

    Deterministic — no LLM call. Same input always produces the same output.
    Commands are taken verbatim from analysis; missing values get explicit
    'Not determinable from source' placeholders rather than invented content.
    """
    name = analysis.get("project_name", "this project")
    desc = analysis.get("description", "")
    lang = analysis.get("primary_language", "")
    frameworks = analysis.get("frameworks", [])
    framework = ", ".join(frameworks) if frameworks else "none detected"
    build_sys = analysis.get("build_system", "")

    def _cmd(key: str) -> str:
        val = analysis.get(key, "")
        if val and val not in ("TODO: verify", ""):
            return val
        return "Not determinable from source"

    naming = analysis.get("naming_convention", "")
    structure = analysis.get("structure_type", "")
    source_dirs = analysis.get("source_directories", [])
    test_dir = analysis.get("test_directory", "")
    entry = analysis.get("entry_point", "")
    restricted = analysis.get("restricted_write_paths", [])
    domain_concepts = analysis.get("domain_concepts", [])

    lines = [f"# {name}", ""]

    lines += [
        "## Project overview",
        desc or "<!-- Fill in: what this project does for its end users -->",
        "",
    ]

    lines += [
        "## Language and framework",
        f"- Primary language: {lang or 'unknown'}",
        f"- Framework: {framework}",
        f"- Build system: {build_sys or 'unknown'}",
        "",
    ]

    lines += [
        "## Critical commands",
        f"- Install: {_cmd('install_command')}",
        f"- Build: {_cmd('build_command')}",
        f"- Test: {_cmd('test_command')}",
        f"- Run locally: {_cmd('run_command')}",
        "",
    ]

    conventions_parts = []
    if naming:
        conventions_parts.append(f"Naming: {naming}")
    if structure:
        conventions_parts.append(f"Structure: {structure}")
    if source_dirs:
        conventions_parts.append(f"Source directories: {', '.join(source_dirs)}")
    lines += [
        "## Code conventions",
        "\n".join(conventions_parts)
        if conventions_parts
        else "<!-- Fill in: naming, file structure, patterns -->",
        "",
    ]

    dir_lines = []
    if entry:
        dir_lines.append(f"- Entry point: {entry}")
    if test_dir:
        dir_lines.append(f"- Tests: {test_dir}")
    lines += [
        "## Files and directories",
        "\n".join(dir_lines) if dir_lines else "<!-- Fill in: key file locations -->",
        "",
    ]

    lines += [
        "## Do not modify",
        "\n".join(f"- {p}" for p in restricted)
        if restricted
        else "Not determinable from source — fill in agent-context.json static.restricted_write_paths",
        "",
    ]

    concept_lines = [
        f"- {c['term']}: {c['definition']}" for c in domain_concepts if isinstance(c, dict)
    ]
    lines += [
        "## Domain concepts",
        "\n".join(concept_lines)
        if concept_lines
        else "Not determinable from source — fill in agent-context.json static.domain_concepts",
        "",
    ]

    return "\n".join(lines)


# ── skills/ ───────────────────────────────────────────────────────────────────

_LINTERS = {
    "ruff",
    "eslint",
    "checkstyle",
    "pylint",
    "flake8",
    "rubocop",
    "golangci-lint",
    "clippy",
}
_MIGRATION_FRAMEWORKS = {"flyway", "alembic", "liquibase", "migrate", "knex"}
_DOCKER_SIGNALS = {"docker", "docker-compose"}
_PACKAGE_MANAGERS = {"pip", "npm", "yarn", "gradle", "maven", "cargo", "bundler", "go"}


def detect_skills(analysis: dict[str, Any]) -> list[str]:
    """Return list of skill names to generate based on repo signals."""
    skills: list[str] = []

    # Always generate these two
    skills.append("run-tests")
    skills.append("build")

    raw_frameworks = analysis.get("frameworks") or []
    frameworks_lower = {f.lower() for f in raw_frameworks if isinstance(f, str)}
    raw_build_sys = analysis.get("build_system", "")
    build_sys = str(raw_build_sys).lower() if raw_build_sys else ""

    # Linter
    if frameworks_lower & _LINTERS:
        skills.append("lint")

    # Docker — check specific config file names, not broad substring matching
    docker_config_files = {"docker-compose.yml", "docker-compose.yaml", "Dockerfile"}
    file_tree = set(analysis.get("file_tree") or [])
    config_file_keys = set((analysis.get("config_files") or {}).keys())
    has_docker = bool(
        docker_config_files & file_tree
        or docker_config_files & config_file_keys
        or {"docker", "docker-compose"} & frameworks_lower
    )
    if has_docker:
        skills.append("start-local")

    # Migration framework
    if frameworks_lower & _MIGRATION_FRAMEWORKS:
        skills.append("run-migrations")

    # CI
    if analysis.get("has_ci", False):
        skills.append("run-ci")

    # OpenAPI
    if analysis.get("has_openapi", False):
        skills.append("generate-api-docs")

    # Package manager
    if build_sys in _PACKAGE_MANAGERS:
        skills.append("add-dependency")

    # Deduplicate while preserving order
    seen: set[str] = set()
    result: list[str] = []
    for s in skills:
        if s not in seen:
            seen.add(s)
            result.append(s)
    return result


_SKILL_DESCRIPTIONS = {
    "run-tests": "Run the full test suite with project-configured settings.",
    "build": "Build the project artifacts.",
    "lint": "Run the linter and fix reported issues.",
    "start-local": "Start the application locally using Docker.",
    "run-migrations": "Apply pending database migrations.",
    "run-ci": "Trigger or simulate the CI pipeline.",
    "generate-api-docs": "Generate or update API documentation from the OpenAPI spec.",
    "add-dependency": "Add a new dependency to the project.",
}


def generate_skill_file(model: str, skill_name: str, analysis: dict[str, Any]) -> str:
    desc = _SKILL_DESCRIPTIONS.get(skill_name, f"Execute the {skill_name} workflow.")
    return _call(
        model,
        f"""\
Generate a skill file named '{skill_name}' for this repository.

A skill file is a self-contained instruction set for a specific repo action,
used by Claude Code as a slash-command reference.

Repository analysis:
{_compact_analysis_for_prompt(analysis)}

The skill name is: {skill_name}
The skill description is: {desc}

{_GROUNDING_RULES}

Write the file using EXACTLY this structure — no deviations:

---
name: {skill_name}
description: {desc}
---

## When to use this skill

<One sentence trigger condition.>

## Steps

1. <First step — use the EXACT command from the analysis above if available>
2. <Second step>
3. <Validation step — how to confirm success>

## Expected output

<What a successful run looks like. Be specific.>

## Common failures

- **<Failure condition>**: <How to recover>
- **<Failure condition>**: <How to recover>

RULES:
- Commands MUST come from the analysis JSON above (test_command, build_command, install_command, run_command, etc.).
- If a command cannot be determined, write: "Command not determinable from source — check your project's documentation."
- Do NOT invent commands. Do NOT use generic placeholders like "npm run build" unless that is the actual command in the analysis.
- Omit the "## Notes" section unless there is a specific project caveat from the analysis worth flagging.
- Output only the file content — no preamble, no explanation.\
""",
        max_tokens=1000,
    )


# ── hooks/ ────────────────────────────────────────────────────────────────────


def detect_hooks(analysis: dict[str, Any]) -> list[str]:
    """Return list of hook names to generate based on repo signals."""
    hooks: list[str] = ["session-start", "pre-tool-call"]

    test_cmd = analysis.get("test_command", "")
    if test_cmd and test_cmd not in (
        "TODO: verify",
        "TODO: no test suite detected — add tests first",
    ):
        hooks.append("post-test")

    frameworks_lower = {f.lower() for f in analysis.get("frameworks", [])}
    if frameworks_lower & _LINTERS:
        hooks.append("pre-commit")

    return hooks


_HOOK_TRIGGERS = {
    "session-start": "At the start of every Claude Code session",
    "pre-tool-call": "Before any tool call that writes files",
    "post-test": "After running the test command",
    "pre-commit": "Before a git commit",
}


def generate_hook_file(
    model: str,
    hook_name: str,
    analysis: dict[str, Any],
    generated_files: set[str] | None = None,
) -> str:
    trigger = _HOOK_TRIGGERS.get(hook_name, f"When {hook_name} event fires")
    generated_files = generated_files or set()

    context_note = (
        "Load current state from agent-context.json"
        if "agent-context.json" in generated_files
        else "agent-context.json not yet generated — run AgentReady first to generate it"
    )
    memory_note = (
        "Check memory/schema.md for session state contract"
        if "memory/schema.md" in generated_files
        else "memory/schema.md not yet generated — run AgentReady first to generate it"
    )

    return _call(
        model,
        f"""\
Generate a hook file named '{hook_name}' for this repository.

A hook file defines actions Claude Code takes at a specific lifecycle point.

Repository analysis:
{_compact_analysis_for_prompt(analysis)}

The hook name is: {hook_name}
The trigger is: {trigger}

Context availability:
- agent-context.json: {context_note}
- memory/schema.md: {memory_note}

{_GROUNDING_RULES}

Write the file using EXACTLY this structure — no deviations:

---
name: {hook_name}
trigger: {trigger}
---

## Purpose

<One sentence describing what this hook does and why it exists for this specific repo.>

## Actions

1. <Specific action grounded in this repo's configuration>
2. <Second action>

## Context loaded

<What information this hook makes available to the agent.>

## Skipped when

<Conditions under which this hook should not execute.>

RULES:
- All actions must be grounded in this specific repo's configuration (commands, paths, restricted_write_paths).
- Use exact commands from the analysis where relevant.
- For 'pre-tool-call': always reference restricted_write_paths from the analysis.
- For 'post-test': always reference the test_command from the analysis.
- For 'pre-commit': always reference the linter command from the analysis.
- Include "AGENT_SKIP_HOOKS=true environment variable is set" as one skipped-when condition.
- Only reference agent-context.json or memory/schema.md if the context availability above confirms they exist.
- Output only the file content — no preamble, no explanation.\
""",
        max_tokens=800,
    )


# ── .github/dependabot.yml ────────────────────────────────────────────────────


_ECOSYSTEM_MAP: dict[str, str] = {
    # build_system → dependabot package-ecosystem
    "npm": "npm",
    "yarn": "npm",
    "pip": "pip",
    "cargo": "cargo",
    "maven": "maven",
    "gradle": "gradle",
    "bundler": "bundler",
    "go": "gomod",
    # primary_language fallbacks
    "python": "pip",
    "javascript": "npm",
    "typescript": "npm",
    "rust": "cargo",
    "java": "maven",
    "ruby": "bundler",
}


def build_dependabot_yml(analysis: dict[str, Any]) -> str:
    """Generate .github/dependabot.yml for automatic dependency updates."""
    build_sys = analysis.get("build_system", "unknown").lower()
    lang = analysis.get("primary_language", "").lower()
    ecosystem = _ECOSYSTEM_MAP.get(build_sys) or _ECOSYSTEM_MAP.get(lang) or "pip"

    updates = [
        {
            "package-ecosystem": ecosystem,
            "directory": "/",
            "schedule": {"interval": "weekly"},
            "groups": {"all-dependencies": {"patterns": ["*"]}},
        },
        # Always keep GitHub Actions up to date
        {
            "package-ecosystem": "github-actions",
            "directory": "/",
            "schedule": {"interval": "monthly"},
            "groups": {"github-actions": {"patterns": ["*"]}},
        },
    ]

    import yaml  # pyyaml is a transitive dep of litellm

    body = yaml.dump({"version": 2, "updates": updates}, default_flow_style=False, sort_keys=False)
    return f"# Auto-generated by AgentReady — safe to edit\n{body}"


# ── Orchestrator ──────────────────────────────────────────────────────────────


class LLMGenerator:
    def __init__(
        self,
        target: Path,
        analysis: dict[str, Any],
        generation_model: str,
        dry_run: bool = False,
        force: bool = False,
        quiet: bool = False,
    ):
        self.target = target
        self.analysis = analysis
        self.model = generation_model
        self.dry_run = dry_run
        self.force = force
        self.quiet = quiet
        self.generated: list[tuple[str, str]] = []

    def generate_all(self) -> list[tuple[str, str]]:
        self._agent_context()
        self._agents_md()
        self._claude_md()
        self._cursorrules()
        self._copilot_instructions()
        self._system_prompt()
        self._mcp_json()
        self._memory_schema()
        self._skills()
        self._hooks()
        self._refresh_context_script()
        self._dependabot_yml()
        self._custom_questions_starter()
        self._openapi_stub()
        self._codeowners()
        return self.generated

    def generate_only(self, category: str) -> list[tuple[str, str]]:
        dispatch = {
            "agents": lambda: (
                self._agents_md(),
                self._claude_md(),
                self._copilot_instructions(),
                self._system_prompt(),
            ),
            "context": lambda: (
                self._agent_context(),
                self._refresh_context_script(),
            ),
            "memory": self._memory_schema,
        }
        fn = dispatch.get(category)
        if fn is None:
            raise ValueError(f"Unknown category: {category!r}")
        fn()
        return self.generated

    def _agent_context(self) -> None:
        existing_static: dict[str, Any] | None = None
        ctx_path = self.target / "agent-context.json"
        if ctx_path.exists():
            try:
                existing = json.loads(ctx_path.read_text())
                existing_static = existing.get("static")
                if not self.quiet and existing_static:
                    print("  ℹ️  Existing static section found — preserving it")
            except Exception:
                pass
        content = build_agent_context(self.analysis, existing_static)
        self._write("agent-context.json", content, always_overwrite=True)

    def _agents_md(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating AGENTS.md...")
        self._write("AGENTS.md", generate_agents_md(self.model, self.analysis))

    def _claude_md(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating CLAUDE.md...")
        self._write("CLAUDE.md", generate_claude_md(self.model, self.analysis))

    def _cursorrules(self) -> None:
        self._write(".cursorrules", build_cursorrules(self.analysis))

    def _skills(self) -> None:
        skill_names = detect_skills(self.analysis)
        for skill_name in skill_names:
            if not self.quiet:
                print(f"  ✍️  Generating skills/{skill_name}.md...")
            try:
                content = generate_skill_file(self.model, skill_name, self.analysis)
                self._write(f"skills/{skill_name}.md", content)
            except Exception as e:
                if not self.quiet:
                    print(f"  ⚠️  Failed to generate skills/{skill_name}.md: {e}. Skipping.")
                self.generated.append((f"skills/{skill_name}.md", "⚠️  Skipped (error)"))

    def _hooks(self) -> None:
        hook_names = detect_hooks(self.analysis)
        generated_paths = {path for path, _ in self.generated}
        for hook_name in hook_names:
            if not self.quiet:
                print(f"  ✍️  Generating hooks/{hook_name}.md...")
            try:
                content = generate_hook_file(self.model, hook_name, self.analysis, generated_paths)
                self._write(f"hooks/{hook_name}.md", content)
            except Exception as e:
                if not self.quiet:
                    print(f"  ⚠️  Failed to generate hooks/{hook_name}.md: {e}. Skipping.")
                self.generated.append((f"hooks/{hook_name}.md", "⚠️  Skipped (error)"))

    def _copilot_instructions(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating .github/copilot-instructions.md...")
        self._write(
            ".github/copilot-instructions.md",
            generate_copilot_instructions(self.model, self.analysis),
        )

    def _system_prompt(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating system_prompt.md...")
        self._write("system_prompt.md", generate_system_prompt(self.model, self.analysis))

    def _mcp_json(self) -> None:
        self._write("mcp.json", generate_mcp_json(self.analysis))

    def _memory_schema(self) -> None:
        if not self.quiet:
            print("  ✍️  Generating memory/schema.md...")
        self._write("memory/schema.md", generate_memory_schema(self.model, self.analysis))

    def _refresh_context_script(self) -> None:
        self._write(
            "tools/refresh_context.py",
            build_refresh_context_script(self.analysis),
        )

    def _dependabot_yml(self) -> None:
        self._write(
            ".github/dependabot.yml",
            build_dependabot_yml(self.analysis),
        )

    def _custom_questions_starter(self) -> None:
        self._write(
            ".agent-ready/custom_questions.json",
            build_custom_questions_starter(self.analysis),
        )

    def _openapi_stub(self) -> None:
        # Only generate for REST API repos that don't already have an OpenAPI spec
        if not self.analysis.get("has_openapi", False) and _is_rest_api(self.analysis):
            self._write("openapi.yaml", build_openapi_stub(self.analysis))

    def _codeowners(self) -> None:
        self._write(".github/CODEOWNERS", build_codeowners(self.analysis))

    def _write(self, rel_path: str, content: str, always_overwrite: bool = False) -> None:
        full_path = self.target / rel_path
        already_exists = full_path.exists()

        if already_exists and not self.force and not always_overwrite:
            if not self.quiet:
                print(f"  ⏭️  {rel_path} (exists — use --force to overwrite)")
            self.generated.append((rel_path, "⏭️  Skipped"))
        elif self.dry_run:
            if not self.quiet:
                print(f"  📝 [dry-run] {rel_path}")
            self.generated.append((rel_path, "📝 (dry-run)"))
        else:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            status = "🔄 Updated" if already_exists else "✅ Created"
            if not self.quiet:
                print(f"  {status[:2]} {rel_path}")
            self.generated.append((rel_path, status))
